module.exports.dataRuche = [
	{
		"id_enregistrement":"Id",
		"numero_ruche":"Ruche",
		"position_gps_ruche":"Position GPS",
		"date_enregistrement":"Date de l'enregistrement",
		"masse":"Masse de la ruche (kg)",
		"temperature_ext":"Temperature extérieur",
		"humidite_ext":"Humidite extérieur",
		"nb_sortie":"Nbr de sorties d'abeilles",
		"nb_entree":"Nbr d'entrés d'abeilles",
		"nb_repas":"Nbr d'abeilles s'étant nourries",
		"temperature_int":"Temperature intérieur",
		"humidite_int":"Humidité intérieur",
		"couleur":"Couleur du sol de la ruche",
		"gaz":"Taux de gaz"
	},
	{
		"id_enregistrement":1,
		"numero_ruche":1,
		"position_gps_ruche":"2.678,4.678",
		"date_enregistrement":"2019-07-14",
		"masse":65,
		"temperature_ext":25,
		"humidite_ext":48,
		"nb_sortie":56,
		"nb_entree":78,
		"nb_repas":2,
		"temperature_int":39,
		"humidite_int":35,
		"couleur":"brun",
		"gaz":"none"
	},
	{
		"id_enregistrement":2,
		"numero_ruche":1,
		"position_gps_ruche":"2.678,4.678",
		"date_enregistrement":"2019-07-15",
		"masse":66,
		"temperature_ext":24,
		"humidite_ext":46,
		"nb_sortie":52,
		"nb_entree":68,
		"nb_repas":8,
		"temperature_int":37,
		"humidite_int":39,
		"couleur":"brun",
		"gaz":"none"
	},
	{
		"id_enregistrement":3,
		"numero_ruche":1,
		"position_gps_ruche":"2.678,4.678",
		"date_enregistrement":"2019-07-16",
		"masse":68,
		"temperature_ext":23.5,
		"humidite_ext":51,
		"nb_sortie":45,
		"nb_entree":73,
		"nb_repas":6,
		"temperature_int":36,
		"humidite_int":37,
		"couleur":"brun",
		"gaz":"none"
	},
	{
		"id_enregistrement":4,
		"numero_ruche":1,
		"position_gps_ruche":"2.678,4.678",
		"date_enregistrement":"2019-07-17",
		"masse":73,
		"temperature_ext":24.5,
		"humidite_ext":51,
		"nb_sortie":45,
		"nb_entree":73,
		"nb_repas":6,
		"temperature_int":36,
		"humidite_int":37,
		"couleur":"brun",
		"gaz":"none"
	},
	{
		"id_enregistrement":5,
		"numero_ruche":1,
		"position_gps_ruche":"2.678,4.678",
		"date_enregistrement":"2019-07-18",
		"masse":75,
		"temperature_ext":25.8,
		"humidite_ext":51,
		"nb_sortie":45,
		"nb_entree":73,
		"nb_repas":6,
		"temperature_int":36.8,
		"humidite_int":3.8,
		"couleur":"brun",
		"gaz":"none"
	},
	{
		"id_enregistrement":6,
		"numero_ruche":1,
		"position_gps_ruche":"2.678,4.678",
		"date_enregistrement":"2019-07-19",
		"masse":75,
		"temperature_ext":25.8,
		"humidite_ext":51,
		"nb_sortie":45,
		"nb_entree":73,
		"nb_repas":6,
		"temperature_int":36.3,
		"humidite_int":37.7,
		"couleur":"brun",
		"gaz":"none"
	}

]

