module.exports.dataLogs = [
  {
    "id_enregistrement": 0,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 15:11:03",
    "masse": 65,
    "temperature_ext": 22,
    "humidite_ext": 69,
    "nb_sortie": 168,
    "nb_entree": 170,
    "nb_repas": 5,
    "temperature_int": 22,
    "humidite_int": 69,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 1,
    "id_ruche": 4,
    "date_enregistrement": "30 Jul 2019 11:35:55",
    "masse": 67,
    "temperature_ext": 23,
    "humidite_ext": 69,
    "nb_sortie": 169,
    "nb_entree": 171,
    "nb_repas": 1,
    "temperature_int": 30,
    "humidite_int": 64,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 2,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 21:48:24",
    "masse": 66,
    "temperature_ext": 28,
    "humidite_ext": 65,
    "nb_sortie": 170,
    "nb_entree": 163,
    "nb_repas": 5,
    "temperature_int": 24,
    "humidite_int": 79,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 3,
    "id_ruche": 3,
    "date_enregistrement": "31 Jul 2019 21:44:24",
    "masse": 60,
    "temperature_ext": 26,
    "humidite_ext": 60,
    "nb_sortie": 174,
    "nb_entree": 164,
    "nb_repas": 5,
    "temperature_int": 26,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 4,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 09:35:45",
    "masse": 75,
    "temperature_ext": 27,
    "humidite_ext": 77,
    "nb_sortie": 173,
    "nb_entree": 175,
    "nb_repas": 1,
    "temperature_int": 22,
    "humidite_int": 65,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 5,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 04:30:39",
    "masse": 75,
    "temperature_ext": 30,
    "humidite_ext": 67,
    "nb_sortie": 168,
    "nb_entree": 172,
    "nb_repas": 5,
    "temperature_int": 24,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 6,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 14:51:01",
    "masse": 72,
    "temperature_ext": 28,
    "humidite_ext": 77,
    "nb_sortie": 165,
    "nb_entree": 169,
    "nb_repas": 2,
    "temperature_int": 25,
    "humidite_int": 69,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 7,
    "id_ruche": 5,
    "date_enregistrement": "30 Jul 2019 23:21:42",
    "masse": 69,
    "temperature_ext": 29,
    "humidite_ext": 80,
    "nb_sortie": 177,
    "nb_entree": 174,
    "nb_repas": 3,
    "temperature_int": 26,
    "humidite_int": 68,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 8,
    "id_ruche": 1,
    "date_enregistrement": "31 Jul 2019 06:35:47",
    "masse": 70,
    "temperature_ext": 21,
    "humidite_ext": 76,
    "nb_sortie": 175,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 27,
    "humidite_int": 68,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 9,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 06:28:46",
    "masse": 66,
    "temperature_ext": 26,
    "humidite_ext": 73,
    "nb_sortie": 163,
    "nb_entree": 180,
    "nb_repas": 5,
    "temperature_int": 26,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 10,
    "id_ruche": 3,
    "date_enregistrement": "29 Jul 2019 14:46:01",
    "masse": 74,
    "temperature_ext": 26,
    "humidite_ext": 78,
    "nb_sortie": 168,
    "nb_entree": 170,
    "nb_repas": 1,
    "temperature_int": 25,
    "humidite_int": 75,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 11,
    "id_ruche": 5,
    "date_enregistrement": "30 Jul 2019 19:46:36",
    "masse": 67,
    "temperature_ext": 20,
    "humidite_ext": 78,
    "nb_sortie": 173,
    "nb_entree": 180,
    "nb_repas": 1,
    "temperature_int": 25,
    "humidite_int": 70,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 12,
    "id_ruche": 4,
    "date_enregistrement": "30 Jul 2019 13:13:45",
    "masse": 75,
    "temperature_ext": 20,
    "humidite_ext": 67,
    "nb_sortie": 165,
    "nb_entree": 177,
    "nb_repas": 3,
    "temperature_int": 30,
    "humidite_int": 74,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 13,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 12:01:05",
    "masse": 60,
    "temperature_ext": 28,
    "humidite_ext": 60,
    "nb_sortie": 176,
    "nb_entree": 174,
    "nb_repas": 1,
    "temperature_int": 28,
    "humidite_int": 76,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 14,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 15:54:52",
    "masse": 70,
    "temperature_ext": 24,
    "humidite_ext": 67,
    "nb_sortie": 161,
    "nb_entree": 162,
    "nb_repas": 4,
    "temperature_int": 28,
    "humidite_int": 69,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 15,
    "id_ruche": 4,
    "date_enregistrement": "30 Jul 2019 20:21:43",
    "masse": 75,
    "temperature_ext": 27,
    "humidite_ext": 66,
    "nb_sortie": 169,
    "nb_entree": 164,
    "nb_repas": 3,
    "temperature_int": 27,
    "humidite_int": 75,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 16,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 06:57:26",
    "masse": 75,
    "temperature_ext": 27,
    "humidite_ext": 62,
    "nb_sortie": 179,
    "nb_entree": 164,
    "nb_repas": 1,
    "temperature_int": 23,
    "humidite_int": 77,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 17,
    "id_ruche": 2,
    "date_enregistrement": "31 Jul 2019 23:02:35",
    "masse": 71,
    "temperature_ext": 29,
    "humidite_ext": 71,
    "nb_sortie": 163,
    "nb_entree": 177,
    "nb_repas": 3,
    "temperature_int": 25,
    "humidite_int": 80,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 18,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 21:01:22",
    "masse": 62,
    "temperature_ext": 25,
    "humidite_ext": 60,
    "nb_sortie": 172,
    "nb_entree": 160,
    "nb_repas": 4,
    "temperature_int": 24,
    "humidite_int": 63,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 19,
    "id_ruche": 1,
    "date_enregistrement": "28 Jul 2019 21:07:12",
    "masse": 75,
    "temperature_ext": 29,
    "humidite_ext": 62,
    "nb_sortie": 167,
    "nb_entree": 180,
    "nb_repas": 4,
    "temperature_int": 28,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 20,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 09:16:55",
    "masse": 63,
    "temperature_ext": 28,
    "humidite_ext": 75,
    "nb_sortie": 180,
    "nb_entree": 173,
    "nb_repas": 1,
    "temperature_int": 29,
    "humidite_int": 65,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 21,
    "id_ruche": 1,
    "date_enregistrement": "30 Jul 2019 12:22:45",
    "masse": 68,
    "temperature_ext": 28,
    "humidite_ext": 73,
    "nb_sortie": 169,
    "nb_entree": 175,
    "nb_repas": 2,
    "temperature_int": 29,
    "humidite_int": 63,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 22,
    "id_ruche": 2,
    "date_enregistrement": "30 Jul 2019 23:53:58",
    "masse": 67,
    "temperature_ext": 27,
    "humidite_ext": 60,
    "nb_sortie": 160,
    "nb_entree": 180,
    "nb_repas": 3,
    "temperature_int": 22,
    "humidite_int": 77,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 23,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 21:10:45",
    "masse": 63,
    "temperature_ext": 29,
    "humidite_ext": 71,
    "nb_sortie": 166,
    "nb_entree": 166,
    "nb_repas": 1,
    "temperature_int": 25,
    "humidite_int": 80,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 24,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 17:33:56",
    "masse": 74,
    "temperature_ext": 23,
    "humidite_ext": 67,
    "nb_sortie": 160,
    "nb_entree": 163,
    "nb_repas": 4,
    "temperature_int": 21,
    "humidite_int": 62,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 25,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 21:12:09",
    "masse": 65,
    "temperature_ext": 21,
    "humidite_ext": 73,
    "nb_sortie": 160,
    "nb_entree": 172,
    "nb_repas": 1,
    "temperature_int": 23,
    "humidite_int": 70,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 26,
    "id_ruche": 2,
    "date_enregistrement": "30 Jul 2019 19:26:25",
    "masse": 74,
    "temperature_ext": 30,
    "humidite_ext": 67,
    "nb_sortie": 164,
    "nb_entree": 165,
    "nb_repas": 4,
    "temperature_int": 25,
    "humidite_int": 62,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 27,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 09:24:38",
    "masse": 68,
    "temperature_ext": 21,
    "humidite_ext": 65,
    "nb_sortie": 160,
    "nb_entree": 166,
    "nb_repas": 2,
    "temperature_int": 28,
    "humidite_int": 64,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 28,
    "id_ruche": 1,
    "date_enregistrement": "30 Jul 2019 04:47:58",
    "masse": 75,
    "temperature_ext": 30,
    "humidite_ext": 75,
    "nb_sortie": 175,
    "nb_entree": 173,
    "nb_repas": 1,
    "temperature_int": 29,
    "humidite_int": 63,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 29,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 19:41:31",
    "masse": 66,
    "temperature_ext": 29,
    "humidite_ext": 78,
    "nb_sortie": 175,
    "nb_entree": 180,
    "nb_repas": 2,
    "temperature_int": 26,
    "humidite_int": 79,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 30,
    "id_ruche": 1,
    "date_enregistrement": "30 Jul 2019 10:47:47",
    "masse": 60,
    "temperature_ext": 21,
    "humidite_ext": 80,
    "nb_sortie": 180,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 30,
    "humidite_int": 71,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 31,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 10:11:39",
    "masse": 63,
    "temperature_ext": 28,
    "humidite_ext": 64,
    "nb_sortie": 165,
    "nb_entree": 165,
    "nb_repas": 2,
    "temperature_int": 28,
    "humidite_int": 66,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 32,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 13:10:33",
    "masse": 64,
    "temperature_ext": 23,
    "humidite_ext": 66,
    "nb_sortie": 162,
    "nb_entree": 172,
    "nb_repas": 3,
    "temperature_int": 22,
    "humidite_int": 77,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 33,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 22:40:31",
    "masse": 62,
    "temperature_ext": 29,
    "humidite_ext": 68,
    "nb_sortie": 161,
    "nb_entree": 171,
    "nb_repas": 3,
    "temperature_int": 30,
    "humidite_int": 71,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 34,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 17:40:46",
    "masse": 72,
    "temperature_ext": 24,
    "humidite_ext": 69,
    "nb_sortie": 174,
    "nb_entree": 174,
    "nb_repas": 2,
    "temperature_int": 21,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 35,
    "id_ruche": 3,
    "date_enregistrement": "29 Jul 2019 17:32:26",
    "masse": 73,
    "temperature_ext": 23,
    "humidite_ext": 61,
    "nb_sortie": 162,
    "nb_entree": 171,
    "nb_repas": 2,
    "temperature_int": 23,
    "humidite_int": 65,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 36,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 21:20:14",
    "masse": 72,
    "temperature_ext": 30,
    "humidite_ext": 74,
    "nb_sortie": 163,
    "nb_entree": 179,
    "nb_repas": 4,
    "temperature_int": 20,
    "humidite_int": 73,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 37,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 14:31:30",
    "masse": 66,
    "temperature_ext": 25,
    "humidite_ext": 61,
    "nb_sortie": 180,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 22,
    "humidite_int": 60,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 38,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 20:51:21",
    "masse": 66,
    "temperature_ext": 30,
    "humidite_ext": 79,
    "nb_sortie": 176,
    "nb_entree": 179,
    "nb_repas": 2,
    "temperature_int": 25,
    "humidite_int": 72,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 39,
    "id_ruche": 1,
    "date_enregistrement": "28 Jul 2019 16:11:34",
    "masse": 67,
    "temperature_ext": 22,
    "humidite_ext": 75,
    "nb_sortie": 174,
    "nb_entree": 169,
    "nb_repas": 5,
    "temperature_int": 24,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 40,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 23:12:27",
    "masse": 60,
    "temperature_ext": 25,
    "humidite_ext": 67,
    "nb_sortie": 166,
    "nb_entree": 178,
    "nb_repas": 4,
    "temperature_int": 27,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 41,
    "id_ruche": 3,
    "date_enregistrement": "31 Jul 2019 03:15:26",
    "masse": 61,
    "temperature_ext": 29,
    "humidite_ext": 67,
    "nb_sortie": 162,
    "nb_entree": 180,
    "nb_repas": 4,
    "temperature_int": 26,
    "humidite_int": 69,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 42,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 04:58:37",
    "masse": 67,
    "temperature_ext": 24,
    "humidite_ext": 65,
    "nb_sortie": 164,
    "nb_entree": 167,
    "nb_repas": 5,
    "temperature_int": 22,
    "humidite_int": 73,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 43,
    "id_ruche": 5,
    "date_enregistrement": "28 Jul 2019 17:07:36",
    "masse": 60,
    "temperature_ext": 28,
    "humidite_ext": 71,
    "nb_sortie": 175,
    "nb_entree": 167,
    "nb_repas": 4,
    "temperature_int": 26,
    "humidite_int": 71,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 44,
    "id_ruche": 2,
    "date_enregistrement": "30 Jul 2019 00:24:42",
    "masse": 69,
    "temperature_ext": 23,
    "humidite_ext": 61,
    "nb_sortie": 176,
    "nb_entree": 178,
    "nb_repas": 1,
    "temperature_int": 21,
    "humidite_int": 70,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 45,
    "id_ruche": 2,
    "date_enregistrement": "30 Jul 2019 21:33:57",
    "masse": 65,
    "temperature_ext": 26,
    "humidite_ext": 60,
    "nb_sortie": 175,
    "nb_entree": 166,
    "nb_repas": 5,
    "temperature_int": 27,
    "humidite_int": 63,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 46,
    "id_ruche": 5,
    "date_enregistrement": "28 Jul 2019 18:43:13",
    "masse": 70,
    "temperature_ext": 20,
    "humidite_ext": 67,
    "nb_sortie": 176,
    "nb_entree": 170,
    "nb_repas": 3,
    "temperature_int": 28,
    "humidite_int": 62,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 47,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 14:51:20",
    "masse": 62,
    "temperature_ext": 24,
    "humidite_ext": 71,
    "nb_sortie": 171,
    "nb_entree": 166,
    "nb_repas": 1,
    "temperature_int": 25,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 48,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 21:44:03",
    "masse": 68,
    "temperature_ext": 22,
    "humidite_ext": 73,
    "nb_sortie": 167,
    "nb_entree": 168,
    "nb_repas": 4,
    "temperature_int": 25,
    "humidite_int": 69,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 49,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 17:11:28",
    "masse": 70,
    "temperature_ext": 24,
    "humidite_ext": 78,
    "nb_sortie": 174,
    "nb_entree": 171,
    "nb_repas": 2,
    "temperature_int": 25,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 50,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 04:08:26",
    "masse": 69,
    "temperature_ext": 22,
    "humidite_ext": 67,
    "nb_sortie": 163,
    "nb_entree": 174,
    "nb_repas": 4,
    "temperature_int": 26,
    "humidite_int": 68,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 51,
    "id_ruche": 1,
    "date_enregistrement": "28 Jul 2019 21:22:01",
    "masse": 65,
    "temperature_ext": 27,
    "humidite_ext": 70,
    "nb_sortie": 164,
    "nb_entree": 176,
    "nb_repas": 3,
    "temperature_int": 28,
    "humidite_int": 70,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 52,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 09:27:36",
    "masse": 71,
    "temperature_ext": 26,
    "humidite_ext": 71,
    "nb_sortie": 171,
    "nb_entree": 169,
    "nb_repas": 2,
    "temperature_int": 22,
    "humidite_int": 75,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 53,
    "id_ruche": 3,
    "date_enregistrement": "29 Jul 2019 07:01:55",
    "masse": 72,
    "temperature_ext": 25,
    "humidite_ext": 68,
    "nb_sortie": 178,
    "nb_entree": 165,
    "nb_repas": 5,
    "temperature_int": 28,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 54,
    "id_ruche": 5,
    "date_enregistrement": "28 Jul 2019 19:49:15",
    "masse": 67,
    "temperature_ext": 21,
    "humidite_ext": 70,
    "nb_sortie": 164,
    "nb_entree": 174,
    "nb_repas": 5,
    "temperature_int": 27,
    "humidite_int": 63,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 55,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 22:14:55",
    "masse": 62,
    "temperature_ext": 28,
    "humidite_ext": 78,
    "nb_sortie": 172,
    "nb_entree": 165,
    "nb_repas": 1,
    "temperature_int": 27,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 56,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 06:02:54",
    "masse": 62,
    "temperature_ext": 28,
    "humidite_ext": 64,
    "nb_sortie": 179,
    "nb_entree": 178,
    "nb_repas": 1,
    "temperature_int": 24,
    "humidite_int": 76,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 57,
    "id_ruche": 2,
    "date_enregistrement": "28 Jul 2019 14:34:37",
    "masse": 67,
    "temperature_ext": 30,
    "humidite_ext": 61,
    "nb_sortie": 177,
    "nb_entree": 176,
    "nb_repas": 1,
    "temperature_int": 30,
    "humidite_int": 63,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 58,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 19:09:56",
    "masse": 63,
    "temperature_ext": 29,
    "humidite_ext": 65,
    "nb_sortie": 168,
    "nb_entree": 167,
    "nb_repas": 1,
    "temperature_int": 30,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 59,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 04:09:10",
    "masse": 70,
    "temperature_ext": 20,
    "humidite_ext": 69,
    "nb_sortie": 176,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 21,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 60,
    "id_ruche": 4,
    "date_enregistrement": "30 Jul 2019 16:08:00",
    "masse": 69,
    "temperature_ext": 28,
    "humidite_ext": 73,
    "nb_sortie": 164,
    "nb_entree": 165,
    "nb_repas": 2,
    "temperature_int": 27,
    "humidite_int": 70,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 61,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 20:27:47",
    "masse": 68,
    "temperature_ext": 28,
    "humidite_ext": 64,
    "nb_sortie": 171,
    "nb_entree": 161,
    "nb_repas": 3,
    "temperature_int": 29,
    "humidite_int": 66,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 62,
    "id_ruche": 4,
    "date_enregistrement": "29 Jul 2019 16:56:07",
    "masse": 69,
    "temperature_ext": 26,
    "humidite_ext": 68,
    "nb_sortie": 169,
    "nb_entree": 169,
    "nb_repas": 1,
    "temperature_int": 23,
    "humidite_int": 76,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 63,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 15:30:56",
    "masse": 65,
    "temperature_ext": 21,
    "humidite_ext": 76,
    "nb_sortie": 163,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 21,
    "humidite_int": 75,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 64,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 08:01:37",
    "masse": 62,
    "temperature_ext": 29,
    "humidite_ext": 76,
    "nb_sortie": 167,
    "nb_entree": 160,
    "nb_repas": 4,
    "temperature_int": 24,
    "humidite_int": 72,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 65,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 19:37:41",
    "masse": 70,
    "temperature_ext": 25,
    "humidite_ext": 65,
    "nb_sortie": 174,
    "nb_entree": 165,
    "nb_repas": 1,
    "temperature_int": 30,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 66,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 08:54:47",
    "masse": 65,
    "temperature_ext": 25,
    "humidite_ext": 64,
    "nb_sortie": 164,
    "nb_entree": 170,
    "nb_repas": 3,
    "temperature_int": 26,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 67,
    "id_ruche": 2,
    "date_enregistrement": "30 Jul 2019 12:35:38",
    "masse": 63,
    "temperature_ext": 25,
    "humidite_ext": 73,
    "nb_sortie": 170,
    "nb_entree": 179,
    "nb_repas": 4,
    "temperature_int": 23,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 68,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 02:03:09",
    "masse": 67,
    "temperature_ext": 30,
    "humidite_ext": 80,
    "nb_sortie": 161,
    "nb_entree": 164,
    "nb_repas": 1,
    "temperature_int": 26,
    "humidite_int": 73,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 69,
    "id_ruche": 2,
    "date_enregistrement": "30 Jul 2019 18:45:23",
    "masse": 60,
    "temperature_ext": 22,
    "humidite_ext": 73,
    "nb_sortie": 173,
    "nb_entree": 173,
    "nb_repas": 5,
    "temperature_int": 30,
    "humidite_int": 62,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 70,
    "id_ruche": 2,
    "date_enregistrement": "28 Jul 2019 17:32:46",
    "masse": 65,
    "temperature_ext": 22,
    "humidite_ext": 76,
    "nb_sortie": 178,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 24,
    "humidite_int": 69,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 71,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 09:57:18",
    "masse": 60,
    "temperature_ext": 23,
    "humidite_ext": 71,
    "nb_sortie": 175,
    "nb_entree": 178,
    "nb_repas": 3,
    "temperature_int": 20,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 72,
    "id_ruche": 5,
    "date_enregistrement": "30 Jul 2019 04:15:49",
    "masse": 67,
    "temperature_ext": 27,
    "humidite_ext": 80,
    "nb_sortie": 172,
    "nb_entree": 176,
    "nb_repas": 1,
    "temperature_int": 20,
    "humidite_int": 72,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 73,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 01:24:35",
    "masse": 72,
    "temperature_ext": 30,
    "humidite_ext": 67,
    "nb_sortie": 177,
    "nb_entree": 161,
    "nb_repas": 1,
    "temperature_int": 26,
    "humidite_int": 80,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 74,
    "id_ruche": 1,
    "date_enregistrement": "31 Jul 2019 22:28:44",
    "masse": 67,
    "temperature_ext": 25,
    "humidite_ext": 69,
    "nb_sortie": 162,
    "nb_entree": 170,
    "nb_repas": 3,
    "temperature_int": 29,
    "humidite_int": 72,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 75,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 06:48:40",
    "masse": 75,
    "temperature_ext": 27,
    "humidite_ext": 79,
    "nb_sortie": 166,
    "nb_entree": 177,
    "nb_repas": 5,
    "temperature_int": 22,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 76,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 12:39:38",
    "masse": 75,
    "temperature_ext": 28,
    "humidite_ext": 80,
    "nb_sortie": 167,
    "nb_entree": 167,
    "nb_repas": 4,
    "temperature_int": 22,
    "humidite_int": 71,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 77,
    "id_ruche": 4,
    "date_enregistrement": "29 Jul 2019 18:27:48",
    "masse": 75,
    "temperature_ext": 29,
    "humidite_ext": 75,
    "nb_sortie": 176,
    "nb_entree": 173,
    "nb_repas": 4,
    "temperature_int": 28,
    "humidite_int": 60,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 78,
    "id_ruche": 4,
    "date_enregistrement": "28 Jul 2019 19:16:13",
    "masse": 60,
    "temperature_ext": 22,
    "humidite_ext": 62,
    "nb_sortie": 168,
    "nb_entree": 168,
    "nb_repas": 3,
    "temperature_int": 29,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 79,
    "id_ruche": 2,
    "date_enregistrement": "29 Jul 2019 02:28:03",
    "masse": 74,
    "temperature_ext": 20,
    "humidite_ext": 80,
    "nb_sortie": 179,
    "nb_entree": 162,
    "nb_repas": 5,
    "temperature_int": 21,
    "humidite_int": 80,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 80,
    "id_ruche": 2,
    "date_enregistrement": "28 Jul 2019 19:44:32",
    "masse": 70,
    "temperature_ext": 28,
    "humidite_ext": 73,
    "nb_sortie": 175,
    "nb_entree": 174,
    "nb_repas": 2,
    "temperature_int": 30,
    "humidite_int": 75,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 81,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 10:29:39",
    "masse": 72,
    "temperature_ext": 29,
    "humidite_ext": 73,
    "nb_sortie": 170,
    "nb_entree": 164,
    "nb_repas": 1,
    "temperature_int": 22,
    "humidite_int": 80,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 82,
    "id_ruche": 3,
    "date_enregistrement": "28 Jul 2019 17:00:00",
    "masse": 67,
    "temperature_ext": 27,
    "humidite_ext": 71,
    "nb_sortie": 163,
    "nb_entree": 161,
    "nb_repas": 1,
    "temperature_int": 28,
    "humidite_int": 78,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 83,
    "id_ruche": 3,
    "date_enregistrement": "29 Jul 2019 16:26:21",
    "masse": 63,
    "temperature_ext": 27,
    "humidite_ext": 71,
    "nb_sortie": 168,
    "nb_entree": 162,
    "nb_repas": 2,
    "temperature_int": 22,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 84,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 20:13:16",
    "masse": 74,
    "temperature_ext": 25,
    "humidite_ext": 68,
    "nb_sortie": 172,
    "nb_entree": 180,
    "nb_repas": 3,
    "temperature_int": 28,
    "humidite_int": 76,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 85,
    "id_ruche": 2,
    "date_enregistrement": "28 Jul 2019 23:12:48",
    "masse": 74,
    "temperature_ext": 26,
    "humidite_ext": 62,
    "nb_sortie": 163,
    "nb_entree": 179,
    "nb_repas": 3,
    "temperature_int": 20,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 86,
    "id_ruche": 2,
    "date_enregistrement": "31 Jul 2019 07:05:08",
    "masse": 75,
    "temperature_ext": 20,
    "humidite_ext": 74,
    "nb_sortie": 165,
    "nb_entree": 162,
    "nb_repas": 3,
    "temperature_int": 25,
    "humidite_int": 64,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 87,
    "id_ruche": 1,
    "date_enregistrement": "28 Jul 2019 13:31:08",
    "masse": 64,
    "temperature_ext": 27,
    "humidite_ext": 70,
    "nb_sortie": 164,
    "nb_entree": 178,
    "nb_repas": 5,
    "temperature_int": 23,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 88,
    "id_ruche": 3,
    "date_enregistrement": "30 Jul 2019 14:48:49",
    "masse": 63,
    "temperature_ext": 30,
    "humidite_ext": 60,
    "nb_sortie": 177,
    "nb_entree": 175,
    "nb_repas": 1,
    "temperature_int": 23,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 89,
    "id_ruche": 5,
    "date_enregistrement": "29 Jul 2019 19:45:37",
    "masse": 64,
    "temperature_ext": 30,
    "humidite_ext": 67,
    "nb_sortie": 175,
    "nb_entree": 177,
    "nb_repas": 4,
    "temperature_int": 28,
    "humidite_int": 80,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 90,
    "id_ruche": 1,
    "date_enregistrement": "31 Jul 2019 12:21:32",
    "masse": 62,
    "temperature_ext": 29,
    "humidite_ext": 80,
    "nb_sortie": 161,
    "nb_entree": 180,
    "nb_repas": 5,
    "temperature_int": 26,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 91,
    "id_ruche": 4,
    "date_enregistrement": "31 Jul 2019 08:06:20",
    "masse": 71,
    "temperature_ext": 26,
    "humidite_ext": 66,
    "nb_sortie": 168,
    "nb_entree": 179,
    "nb_repas": 3,
    "temperature_int": 30,
    "humidite_int": 74,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 92,
    "id_ruche": 1,
    "date_enregistrement": "31 Jul 2019 17:58:48",
    "masse": 64,
    "temperature_ext": 28,
    "humidite_ext": 61,
    "nb_sortie": 172,
    "nb_entree": 161,
    "nb_repas": 1,
    "temperature_int": 21,
    "humidite_int": 66,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 93,
    "id_ruche": 4,
    "date_enregistrement": "29 Jul 2019 05:58:48",
    "masse": 60,
    "temperature_ext": 26,
    "humidite_ext": 75,
    "nb_sortie": 174,
    "nb_entree": 175,
    "nb_repas": 3,
    "temperature_int": 30,
    "humidite_int": 61,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 94,
    "id_ruche": 2,
    "date_enregistrement": "31 Jul 2019 00:24:45",
    "masse": 71,
    "temperature_ext": 27,
    "humidite_ext": 67,
    "nb_sortie": 163,
    "nb_entree": 170,
    "nb_repas": 3,
    "temperature_int": 22,
    "humidite_int": 76,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 95,
    "id_ruche": 5,
    "date_enregistrement": "31 Jul 2019 09:06:49",
    "masse": 75,
    "temperature_ext": 26,
    "humidite_ext": 60,
    "nb_sortie": 177,
    "nb_entree": 179,
    "nb_repas": 4,
    "temperature_int": 20,
    "humidite_int": 66,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 96,
    "id_ruche": 1,
    "date_enregistrement": "29 Jul 2019 16:27:19",
    "masse": 71,
    "temperature_ext": 23,
    "humidite_ext": 73,
    "nb_sortie": 166,
    "nb_entree": 163,
    "nb_repas": 3,
    "temperature_int": 30,
    "humidite_int": 67,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 97,
    "id_ruche": 1,
    "date_enregistrement": "30 Jul 2019 05:52:40",
    "masse": 73,
    "temperature_ext": 29,
    "humidite_ext": 74,
    "nb_sortie": 168,
    "nb_entree": 170,
    "nb_repas": 4,
    "temperature_int": 25,
    "humidite_int": 66,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 98,
    "id_ruche": 3,
    "date_enregistrement": "29 Jul 2019 10:18:35",
    "masse": 73,
    "temperature_ext": 28,
    "humidite_ext": 75,
    "nb_sortie": 163,
    "nb_entree": 180,
    "nb_repas": 2,
    "temperature_int": 25,
    "humidite_int": 79,
    "couleur": "brun",
    "gaz": "none"
  },
  {
    "id_enregistrement": 99,
    "id_ruche": 2,
    "date_enregistrement": "31 Jul 2019 05:42:58",
    "masse": 73,
    "temperature_ext": 22,
    "humidite_ext": 67,
    "nb_sortie": 162,
    "nb_entree": 175,
    "nb_repas": 5,
    "temperature_int": 24,
    "humidite_int": 75,
    "couleur": "brun",
    "gaz": "none"
  }
]